cleaning repo
WildCodeSchool/2022-09-JS-Lille-project-3-g1-makesense pull request #1
Opened 2022-12-05 08:58 UTC by guenk

repo clean

2022-12-05 09:04 UTC, Sax593 commented on frontend/src/pages/Home.jsx
> -      <p>Hello Vite + React !</p>
This is not professional

2022-12-05 09:04 UTC, Sax593 requested changes
The project will not use CSS, so all .css files must be deleted.

2022-12-05 09:05 UTC, Sax593 commented on frontend/src/pages/Home.jsx
> +
This is not professional

2022-12-05 09:20 UTC, Sax593 approved these changes, later dismissed
Good job

2022-12-05 09:58 UTC, Sax593 approved these changes
it's ok

2022-12-07 08:02 UTC, LoicBrassart approved these changes
Someunclean code (prtettier conf) but we'll fix it later

2022-12-07 08:02 UTC, LoicBrassart commented on frontend/src/pages/Home/Home.jsx
> +  );
Prettier didn't run on this, you have a conf problem

2022-12-07 08:25 UTC, merged