Backend comment
WildCodeSchool/2022-09-JS-Lille-project-3-g1-makesense pull request #13
Opened 2022-12-15 14:27 UTC by AlexisFLT

2022-12-15 15:53 UTC, Sax593 requested changes
Please add only the files that concern the comments

2022-12-19 13:17 UTC, Sax593 approved these changes, later dismissed

2022-12-20 09:44 UTC, LoicBrassart requested changes
Read your PRs carefully plz

2022-12-20 09:44 UTC, LoicBrassart commented on backend/src/router.js
> +// router.delete("/users/:id", usersControllers.destroy);
Dead code... You just didn't read this, did you ? -_-

2023-01-04 11:04 UTC, Sax593 approved these changes

2023-01-04 13:39 UTC, LoicBrassart approved these changes
SnE

2023-01-05 08:29 UTC, merged