Navbar
WildCodeSchool/2022-09-JS-Lille-project-3-g1-makesense pull request #2
Opened 2022-12-07 08:35 UTC by guenk

Adding a Navbar with styles and burger menu.

2022-12-07 08:45 UTC, Sax593 reviewed
The font and logo images are not used and react router is installed but not used

2022-12-07 08:51 UTC, Sax593 submitted a review, later dismissed
Good job

2022-12-07 12:28 UTC, LoicBrassart requested changes
Some Evils, plz fix'em!

2022-12-07 12:28 UTC, LoicBrassart commented on frontend/src/components/Myspace/Myspace.jsx
> +
Where's my Prettier ? è_é

2022-12-07 12:28 UTC, LoicBrassart commented on frontend/src/pages/Home/Home.jsx
> +
Where !?
୧( ಠ Д ಠ )୨

2022-12-08 13:25 UTC, Sax593 requested changes

2022-12-08 13:25 UTC, Sax593 commented on frontend/src/components/Myspace/Style.scss
> +}
Death Code

2022-12-08 13:32 UTC, Sax593 submitted a review, later dismissed

2022-12-08 15:30 UTC, LoicBrassart commented
Ongoing conflicts, plz fix

2022-12-09 09:32 UTC, Sax593 submitted a review, later dismissed

2022-12-09 10:00 UTC, LoicBrassart approved these changes, later dismissed
SnE

2022-12-09 16:01 UTC, Sax593 approved these changes

2022-12-12 08:24 UTC, LoicBrassart approved these changes
SnE!

2022-12-12 08:31 UTC, merged