Link avatar login
WildCodeSchool/2022-09-JS-Lille-project-3-g1-makesense pull request #24
Opened 2023-01-09 07:57 UTC by guenk

adding preview to avatar

2023-01-09 09:41 UTC, Sax593 requested changes

2023-01-09 09:41 UTC, Sax593 commented on package.json
> +    "axios": "^1.2.2"
Should not be here

2023-01-09 09:41 UTC, Sax593 commented on frontend/src/pages/Home/Home.jsx
>        <section className="titlehome">
Already present on the dev

2023-01-09 09:41 UTC, Sax593 commented on frontend/src/pages/Home/Style.scss
Already present on the dev

2023-01-09 09:41 UTC, Sax593 commented on frontend/src/components/Myspace/Myspace.jsx
>        <Link id="home" className="menu-item" to="/">
This component has rename and merge in dev. Please remove this!

2023-01-09 09:41 UTC, Sax593 commented on frontend/src/components/Myspace/Style.scss
>    padding-top: 2.7em;
This component has rename and merge in dev. Please remove this!

2023-01-09 09:41 UTC, Sax593 commented on frontend/src/App.jsx
> +        <Route path="/sub" element={<SubscriptionForm />} />
Please do not rename the route, /register is more meaningful than /sub

2023-01-09 09:41 UTC, Sax593 commented on backend/package.json
> +    "axios": "^1.2.2",
Should not be here

2023-01-09 13:05 UTC, Sax593 requested changes

2023-01-09 13:05 UTC, Sax593 commented on package.json
> +    "mock-aws-s3": "^4.0.2"
Axios is a frontend dependencies, argon2 is backend dependencies.

2023-01-09 13:05 UTC, Sax593 commented on backend/package.json
> +    "argon2": "^0.30.3",
Don't use, ca you delet this?

2023-01-10 08:27 UTC, Sax593 approved these changes

2023-01-10 10:30 UTC, Sax593 submitted a review, later dismissed

2023-01-10 12:23 UTC, LoicBrassart requested changes
Nope, there are a lot of problems in this PR, how did you manage to commit it ? :raised_eyebrow:

2023-01-10 12:23 UTC, LoicBrassart commented on backend/src/models/UsersManager.js
> +const saltRounds = 10;
-> `.env`

2023-01-10 12:23 UTC, LoicBrassart commented on backend/src/models/UsersManager.js
> +const someOtherPlaintextPassword = "not_bacon";
These variables are useless, aren't they?

2023-01-10 12:23 UTC, LoicBrassart commented on backend/src/models/UsersManager.js
> +const someOtherPlaintextPassword = "not_bacon";
More, they are the example variables from the bcrypt package and are not used in this file

2023-01-10 12:23 UTC, LoicBrassart commented on backend/src/models/UsersManager.js
> +    const hashedPassword = await bcrypt.hash(users.password, 10);
No hardcoded values

2023-01-10 12:23 UTC, LoicBrassart commented on package.json
> +    "mock-aws-s3": "^4.0.2"
And you shouldn't be using Amazon S3

2023-01-19 09:12 UTC, Sax593 approved these changes

2023-01-19 13:04 UTC, LoicBrassart approved these changes
sne

2023-01-19 14:46 UTC, merged