Subscription form
WildCodeSchool/2022-09-JS-Lille-project-3-g1-makesense pull request #3
Opened 2022-12-07 09:53 UTC by AlexisFLT

2022-12-07 10:07 UTC, Sax593 submitted a review, later dismissed
It's ok

2022-12-07 12:30 UTC, LoicBrassart requested changes
Fix your Prettier, damnit! ୧( ಠ Д ಠ )୨

2022-12-07 12:30 UTC, LoicBrassart commented on frontend/src/App.scss
> +
Prettier should have fixed this ಠ_ಠ

2022-12-07 12:30 UTC, LoicBrassart commented on frontend/src/pages/SubscriptionForm/style.scss
> +
Give me back my Prettier! ಠ_ಥ

2022-12-07 12:30 UTC, LoicBrassart commented on frontend/src/pages/SubscriptionForm/style.scss
> +
...

2022-12-07 13:52 UTC, Sax593 approved these changes, later dismissed
It's OK

2022-12-07 15:21 UTC, Sax593 requested changes
Unnecessary space

2022-12-07 15:21 UTC, Sax593 commented on frontend/package.json
> +
Unnecessary space

2022-12-07 15:21 UTC, Sax593 commented on frontend/src/App.jsx
> +
Unnecessary space

2022-12-07 15:39 UTC, Sax593 approved these changes

2022-12-08 10:56 UTC, LoicBrassart approved these changes
Saw no Evil

2022-12-08 11:28 UTC, merged