Polishing all
WildCodeSchool/2022-09-JS-Lille-project-3-g1-makesense pull request #50
Opened 2023-01-25 16:10 UTC by guenk

2023-01-25 16:17 UTC, Sax593 requested changes

2023-01-25 16:17 UTC, Sax593 commented on frontend/src/components/NavBarSuggest/style.scss
> +  text-shadow: 2px 2px black;
Unecessary space

2023-01-25 16:17 UTC, Sax593 commented on frontend/src/components/Timeline/Style.scss
> +
Unecessary space

2023-01-25 16:17 UTC, Sax593 commented on frontend/src/components/Timeline/Style.scss
> +
Unecessary space

2023-01-25 16:19 UTC, Sax593 approved these changes

2023-01-26 10:06 UTC, LoicBrassart approved these changes
SnE

2023-01-26 10:17 UTC, merged