responsive for tablet and phone
WildCodeSchool/2022-09-JS-Lille-project-3-g1-makesense pull request #56
Opened 2023-01-26 15:36 UTC by Fbouchezpro

2023-01-26 15:39 UTC, Sax593 requested changes

2023-01-26 15:39 UTC, Sax593 commented on frontend/src/pages/Thread/Style.scss
> +
Unecessary space

2023-01-27 09:27 UTC, Sax593 approved these changes

2023-01-27 09:33 UTC, LoicBrassart approved these changes
SnE

2023-01-27 09:44 UTC, merged