Newhome
WildCodeSchool/2022-09-JS-Lille-project-3-g1-makesense pull request #6
Opened 2022-12-08 14:24 UTC by guenk

Newhome with navbar and style

2022-12-08 14:35 UTC, Sax593 requested changes

2022-12-08 14:35 UTC, Sax593 commented on frontend/src/pages/Home/Style.scss
> +
Unnecessary space

2022-12-08 14:35 UTC, Sax593 commented on frontend/src/pages/Home/Style.scss
> +
Unnecessary space

2022-12-08 14:37 UTC, Sax593 approved these changes, later dismissed

2022-12-08 16:08 UTC, LoicBrassart submitted a review, later dismissed
SnE

2022-12-08 16:08 UTC, LoicBrassart commented
Didn't see the conflicts, I'll have to re-read this later -_-

2022-12-09 09:30 UTC, Sax593 approved these changes

2022-12-09 10:02 UTC, LoicBrassart approved these changes
SnE

2022-12-09 15:58 UTC, merged