Rework form sugg
WildCodeSchool/2022-09-JS-Lille-project-3-g1-makesense pull request #62
Opened 2023-01-28 14:05 UTC by AlexisFLT

2023-01-28 14:29 UTC, Sax593 submitted a review, later dismissed

2023-01-30 11:04 UTC, LoicBrassart requested changes
One incomprehensible Evil

2023-01-30 11:04 UTC, LoicBrassart commented on frontend/src/pages/Home/Home.jsx
> +  const [, setPriority] = useState(null);
What's this ? You update a state you don't keep

2023-01-30 12:51 UTC, AlexisFLT commented on frontend/src/pages/Home/Home.jsx
> +  const [, setPriority] = useState(null);
yes we know, it was temporary. I will fix it

2023-01-30 12:56 UTC, Sax593 approved these changes

2023-01-30 13:37 UTC, LoicBrassart approved these changes
SnE

2023-01-30 13:49 UTC, merged