Fixmultiplethings
WildCodeSchool/2022-09-JS-Lille-project-3-g1-makesense pull request #65
Opened 2023-01-29 11:10 UTC by guenk

2023-01-29 15:09 UTC, Sax593 requested changes

2023-01-29 15:09 UTC, Sax593 commented on backend/src/app.js
> +        callback(null, true);
Please change callback

2023-01-29 15:09 UTC, Sax593 commented on frontend/src/App.jsx
> +        <Route path="/home" element={<Home />} />
This change is already included in a dedicated PR

2023-01-29 15:09 UTC, Sax593 commented on frontend/src/components/FinalContent/FinalContent.jsx
> +      .get(`${import.meta.env.VITE_BACKEND_URL}/suggests/${id}`)
This change is already included in a dedicated PR

2023-01-29 15:09 UTC, Sax593 commented on frontend/src/components/LoginForm/LoginForm.jsx
> +        navigate("/home");
This change is already included in a dedicated PR

2023-01-29 15:09 UTC, Sax593 commented on frontend/src/components/Nav/Nav.jsx
> +      <Link id="home" className="menu-item" to="/home">
This change is already included in a dedicated PR

2023-01-29 15:09 UTC, Sax593 commented on frontend/src/pages/Register/Register.jsx
> +      });
This change is already included in a dedicated PR

2023-01-30 14:27 UTC, Sax593 submitted a review, later dismissed

2023-01-30 14:31 UTC, Fbouchezpro approved these changes, later dismissed
Sne

2023-01-30 14:59 UTC, LoicBrassart submitted a review, later dismissed
SnE

2023-01-30 15:40 UTC, Sax593 approved these changes

2023-01-30 15:52 UTC, LoicBrassart approved these changes
SnE

2023-01-30 20:24 UTC, merged