Fixcomments
WildCodeSchool/2022-09-JS-Lille-project-3-g1-makesense pull request #76
Opened 2023-02-06 14:01 UTC by Fbouchezpro

2023-02-06 14:06 UTC, Sax593 submitted a review, later dismissed

2023-02-06 14:23 UTC, fantinerudent requested changes

2023-02-06 14:23 UTC, fantinerudent commented on frontend/src/components/Comments/Comments.jsx
> +    // eslint-disable-next-line no-shadow
❌

2023-02-06 14:23 UTC, fantinerudent commented on frontend/src/components/Comments/Comments.jsx
> +          text: "Your comments has be sent",
pourquoi il y a  un S à comment ? ils en envoient forcément plusieurs à la fois?
Ca y'est vous avez décidé de passer au full english?

2023-02-06 14:23 UTC, fantinerudent commented on frontend/src/components/Comments/Comments.jsx
> +          text: "Your comments has be sent",
has been by the way

2023-02-07 09:21 UTC, Fbouchezpro commented on frontend/src/components/Comments/Comments.jsx
> +    // eslint-disable-next-line no-shadow
Done!

2023-02-07 09:22 UTC, Fbouchezpro commented on frontend/src/components/Comments/Comments.jsx
> +          text: "Your comments has be sent",
Done too!

2023-02-07 10:01 UTC, Sax593 submitted a review, later dismissed

2023-02-07 11:16 UTC, fantinerudent approved these changes

2023-02-07 13:26 UTC, Sax593 approved these changes

2023-02-07 13:26 UTC, merged